POST  http://localhost:3000/api/register
Content-Type: application/json

{
    "username": "coki",
    "password": "adachikawai",
    "email": "zoneandika@gmail.com",
    "deskripsi": "sibuk",
    "pp": "/defaultpp.jpg",
    "tag": ["pemula"]

}

###
POST http://localhost:3000/api/user/byEmail
Content-Type: "application/json"

{
    "email": "zoneandika@gmail.com"
}

###
POST http://localhost:3000/api/user/edit
Content-Type: "application/json"

{
    "id": "6542f052865e920968193f85",
    "username": "keqing"
}
###
POST http://localhost:3000/api/user/resetpass
Content-Type: "application/json"

{
    "uid": "65785a1bf4824ba854dd7a3b",
    "oldPassword": "adachikawai",
    "newPassword": "adachikawai123"
}