POST  http://localhost:3000/api/lineup/upload
Content-Type: application/json

{
    "agent": "harbor",
    "ability": 2,
    "map": "ascent",
    "coordinat": ["dasd", "asdasd"],
    "judul": "apa aja",
    "keterangan": "apa aja",
    "tag" : ["easy"],
    "imgAndDes" : [{"img1": "img1sfasfds"}],
    "linkVideo" : "sdsadasdw",
    "idMaker" : "asdalksdakd"

}


### 
POST  http://localhost:3000/api/lineup/get
Content-Type: application/json

{
    "agent": "sova",
    "map": "ascent",
    "status": "defender"

}
 
###
GET http://localhost:3000/api/lineup/like/details?idLineup=6550f1afecca264c1700fe4b

###
POST http://localhost:3000/api/lineup/like
Content-Type: application/json

{
    "idUser": "6542efde865e920968193f77",
    "idLineup": "6550f1afecca264c1700fe4b"
}