POST  http://localhost:3000/api/lineup/upload
Content-Type: application/json

{
    "agent": "sova",
    "ability": 2,
    "map": "ascent",
    "coordinat": ["dasd", "asdasd"],
    "judul": "apa aja",
    "keterangan": "apa aja",
    "tag" : ["easy"],
    "imgAndDes" : [{"img1": "img1sfasfds"}],
    "linkVideo" : "sdsadasdw",
    "idMaker" : "asdalksdakd"

}


### 
POST  http://localhost:3000/api/lineup/get
Content-Type: application/json

{
    "idMaker": "65784bfcf4824ba854dd7a25",
    "viewProfile": true,
    "page": 2
}
 
###
GET http://localhost:3000/api/lineup/like/details?idLineup=6550f1afecca264c1700fe4b

###
POST http://localhost:3000/api/lineup/like
Content-Type: application/json

{
    "clientUsername": "kopihanet",
    "idLineup": "6550f1afecca264c1700fe4b"
}